/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/generate/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * テキスト生成
         * @description Gemini APIを使用してテキストをストリーミング生成
         */
        post: operations["generate_generate_content_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/patent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate From Patent */
        post: operations["generate_from_patent_generate_patent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/idea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Idea */
        post: operations["generate_idea_generate_idea_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat With Context
         * @description 特許文脈を保持したマルチターンチャット
         */
        post: operations["chat_with_context_generate_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patent/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Pdf
         * @description アップロードされたJ-PlatPat由来の特許PDFを処理し、ファイル情報・ID・本文・画像(メタデータ)を返す
         */
        post: operations["upload_pdf_patent_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_pdf_patent_upload_post */
        Body_upload_pdf_patent_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Patent Id */
            patent_id: string;
            /** User Message */
            user_message: string;
            /**
             * Analysis Text
             * @default
             */
            analysis_text: string;
            /**
             * Idea Text
             * @default
             */
            idea_text: string;
        };
        /** GenerateIdeaRequest */
        GenerateIdeaRequest: {
            /** Patent Id */
            patent_id: string;
            /** Explanation Text */
            explanation_text: string;
        };
        /** GeneratePatentRequest */
        GeneratePatentRequest: {
            /** Patent Id */
            patent_id: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Prompt */
            prompt: string;
            /** Tool Mode */
            tool_mode: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PatentContent */
        PatentContent: {
            /**
             * Abstract
             * @description 要約
             */
            abstract: string;
            /**
             * Claims
             * @description 特許請求の範囲
             */
            claims: string;
            /**
             * Tech Field
             * @description 技術分野
             * @default
             */
            tech_field: string;
            /**
             * Background
             * @description 背景技術
             * @default
             */
            background: string;
            /**
             * Problem To Solve
             * @description 解決しようとする課題
             * @default
             */
            problem_to_solve: string;
            /**
             * Means To Solve
             * @description 解決手段
             * @default
             */
            means_to_solve: string;
            /**
             * Effect
             * @description 発明の効果
             * @default
             */
            effect: string;
            /**
             * Drawings Desc
             * @description 図面の簡単な説明
             * @default
             */
            drawings_desc: string;
            /**
             * Embodiments
             * @description 実施形態
             * @default
             */
            embodiments: string;
            /**
             * Symbols Desc
             * @description 符号の説明
             * @default
             */
            symbols_desc: string;
            /**
             * Industrial Applicability
             * @description 産業上の利用可能性
             * @default
             */
            industrial_applicability: string;
            /**
             * Others
             * @description その他のセクション
             */
            others?: {
                [key: string]: string;
            };
        };
        /** PatentImage */
        PatentImage: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Page */
            page: number;
            /** Url */
            url: string;
        };
        /** PatentUploadResponse */
        PatentUploadResponse: {
            /** Filename */
            filename: string;
            /** Patent Id */
            patent_id: string;
            patent_data: components["schemas"]["PatentContent"];
            /** Images */
            images: components["schemas"]["PatentImage"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_generate_content_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_from_patent_generate_patent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePatentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_idea_generate_idea_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateIdeaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_context_generate_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_pdf_patent_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pdf_patent_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
