/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/generate/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Chat
         * @description 統一エンドポイント
         *     - save_context=False (解析・アイデア生成): 履歴を使わず、単発のリクエストとして処理
         *     - save_context=True  (チャット): セッション履歴を読み書きして処理
         *     - PromptManagerを経由してプロンプトを構築し、生成を行う
         */
        post: operations["generate_chat_generate_content_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patent/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Pdf */
        post: operations["upload_pdf_patent_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_pdf_patent_upload_post */
        Body_upload_pdf_patent_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * GenerateRequest
         * @description 統一リクエスト
         */
        GenerateRequest: {
            /**
             * Prompt Type
             * @description 使用するプロンプトテンプレートのID
             */
            prompt_type: string;
            /**
             * Context
             * @description プロンプトに埋め込むためのコンテキスト情報
             */
            context?: {
                [key: string]: string;
            };
            /**
             * User Message
             * @description ユーザー入力
             */
            user_message: string | null;
            /**
             * Session Id
             * @description 既存セッションID
             */
            session_id?: string | null;
            /**
             * Save Context
             * @description 履歴保存モード（False=シングルショット）
             * @default true
             */
            save_context: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PatentContent */
        PatentContent: {
            /**
             * Abstract
             * @description 要約
             */
            abstract: string;
            /**
             * Claims
             * @description 特許請求の範囲
             */
            claims: string;
            /**
             * Tech Field
             * @description 技術分野
             * @default
             */
            tech_field: string;
            /**
             * Background
             * @description 背景技術
             * @default
             */
            background: string;
            /**
             * Problem To Solve
             * @description 解決しようとする課題
             * @default
             */
            problem_to_solve: string;
            /**
             * Means To Solve
             * @description 解決手段
             * @default
             */
            means_to_solve: string;
            /**
             * Effect
             * @description 発明の効果
             * @default
             */
            effect: string;
            /**
             * Drawings Desc
             * @description 図面の簡単な説明
             * @default
             */
            drawings_desc: string;
            /**
             * Embodiments
             * @description 実施形態
             * @default
             */
            embodiments: string;
            /**
             * Symbols Desc
             * @description 符号の説明
             * @default
             */
            symbols_desc: string;
            /**
             * Industrial Applicability
             * @description 産業上の利用可能性
             * @default
             */
            industrial_applicability: string;
            /**
             * Others
             * @description その他のセクション
             */
            others?: {
                [key: string]: string;
            };
        };
        /** PatentImage */
        PatentImage: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Page */
            page: number;
            /** Url */
            url: string;
        };
        /** PatentUploadResponse */
        PatentUploadResponse: {
            /** Filename */
            filename: string;
            /** Patent Id */
            patent_id: string;
            patent_data: components["schemas"]["PatentContent"];
            /** Images */
            images: components["schemas"]["PatentImage"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_chat_generate_content_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_pdf_patent_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pdf_patent_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
