/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Report
         * @description 新規レポート作成（空の雛形を作成して返す）
         */
        post: operations["create_report_reports__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_type}/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description レポート取得
         */
        get: operations["get_report_reports__report_type___report_id__get"];
        /**
         * Update Report
         * @description レポート更新（上書き保存）
         *     IDとTypeの一致を確認してから保存
         */
        put: operations["update_report_reports__report_type___report_id__put"];
        post?: never;
        /**
         * Delete Report
         * @description レポート削除
         */
        delete: operations["delete_report_reports__report_type___report_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_type}/{report_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Assets
         * @description アセットファイル（画像など）のアップロード
         *     戻り値: アクセス用URLのリスト
         */
        post: operations["upload_assets_reports__report_type___report_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_type}/{report_id}/patent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload And Analyze Patent
         * @description 特許PDFをアップロード・解析し、レポート配下に保存する
         *     このAPIが「特許ディレクトリの作成」「画像の保存」「JSONの保存」の責任を持つ
         *     - data.json: テキストデータ
         *     - images.json: 画像メタデータリスト
         */
        post: operations["upload_and_analyze_patent_reports__report_type___report_id__patent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_and_analyze_patent_reports__report_type___report_id__patent_post */
        Body_upload_and_analyze_patent_reports__report_type___report_id__patent_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_assets_reports__report_type___report_id__assets_post */
        Body_upload_assets_reports__report_type___report_id__assets_post: {
            /** Files */
            files: string[];
        };
        /**
         * CreateReportRequest
         * @description レポート作成
         */
        CreateReportRequest: {
            /**
             * Title
             * @description レポートのタイトル
             */
            title: string;
            /**
             * Report Type
             * @description レポートの種類: idea | search | matching
             */
            report_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PatentContent */
        PatentContent: {
            /**
             * Abstract
             * @description 要約
             */
            abstract: string;
            /**
             * Claims
             * @description 特許請求の範囲
             */
            claims: string;
            /**
             * Tech Field
             * @description 技術分野
             * @default
             */
            tech_field: string;
            /**
             * Background
             * @description 背景技術
             * @default
             */
            background: string;
            /**
             * Problem To Solve
             * @description 解決しようとする課題
             * @default
             */
            problem_to_solve: string;
            /**
             * Means To Solve
             * @description 解決手段
             * @default
             */
            means_to_solve: string;
            /**
             * Effect
             * @description 発明の効果
             * @default
             */
            effect: string;
            /**
             * Drawings Desc
             * @description 図面の簡単な説明
             * @default
             */
            drawings_desc: string;
            /**
             * Embodiments
             * @description 実施形態
             * @default
             */
            embodiments: string;
            /**
             * Symbols Desc
             * @description 符号の説明
             * @default
             */
            symbols_desc: string;
            /**
             * Industrial Applicability
             * @description 産業上の利用可能性
             * @default
             */
            industrial_applicability: string;
            /**
             * Others
             * @description その他のセクション
             */
            others?: {
                [key: string]: string;
            };
        };
        /** PatentImage */
        PatentImage: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** PatentUploadResponse */
        PatentUploadResponse: {
            /** Filename */
            filename: string;
            /** Patent Id */
            patent_id: string;
            patent_data: components["schemas"]["PatentContent"];
            /** Images */
            images: components["schemas"]["PatentImage"][];
        };
        /**
         * ReportDocument
         * @description レポート全体構造：中身はブラックボックス（任意のJSONオブジェクト）として許容
         */
        ReportDocument: {
            /** @description レポートのメタデータ */
            metadata: components["schemas"]["ReportMetadata"];
            /**
             * Content
             * @description 任意のJSONオブジェクト
             */
            content?: {
                [key: string]: unknown;
            };
        };
        /**
         * ReportMetadata
         * @description レポートのメタデータ：検索や一覧表示、ルーティングに必要な最低限の情報
         */
        ReportMetadata: {
            /**
             * Report Id
             * @description レポートのID
             */
            report_id: string;
            /**
             * Title
             * @description レポートのタイトル
             */
            title: string;
            /**
             * Report Type
             * @description レポートの種類: idea | search | matching
             */
            report_type: string;
            /**
             * Created At
             * @description レポートの作成日時
             */
            created_at: string;
            /**
             * Updated At
             * @description レポートの更新日時
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_report_reports__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_reports__report_type___report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_type: string;
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_report_reports__report_type___report_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_type: string;
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_report_reports__report_type___report_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_type: string;
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_assets_reports__report_type___report_id__assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_type: string;
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_assets_reports__report_type___report_id__assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_and_analyze_patent_reports__report_type___report_id__patent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_type: string;
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_and_analyze_patent_reports__report_type___report_id__patent_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
